name: Build and deploy documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # this is broken (https://github.com/actions/checkout/issues/1471). very helpful :) -- so we fetch tags seperately in the next step
          fetch-tags: true

      - run: |
          git fetch --prune --unshallow --tags

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          pip install -r ${GITHUB_WORKSPACE}/docs/requirements.txt

        # script is called from meson -- this step *might* not be necessary, but better safe than sorry
      - run: |
          chmod +x ${GITHUB_WORKSPACE}/docs/conf_wrapper.sh

      - name: Build docs
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          setup-options: -Dcore=false -Ddocs=true
          options: --verbose
          meson-version: 1.3.0

      - name: Disable jekyll
        run: |
          touch ${GITHUB_WORKSPACE}/build/docs/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/docs/html
